# Generated by Django 4.2.2 on 2023-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=10)),
                ('father_s_name', models.CharField(max_length=50)),
                ('birth_certificate_no', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
