# Generated by Django 4.2.2 on 2023-06-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
