# Generated by Django 4.2.2 on 2023-06-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerservice',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
